### ISSUE TITLE
Can't extit program after error see log scenario with pyglet-gui

### ISSUE THREAD

**Issue by thomakl** [juliencegarra/OpenMATB#22]
Hi,

If trigger a 'OpenMATB - fatal error !' I can't exit the program with a key pressed.
That would require me to force the exit by killing it.
See the traceback below : 

```
Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x0000017B3C118940>
Traceback (most recent call last):
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 747, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 819, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\__init__.py", line 1352, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\event.py", line 408, in dispatch_event
    if handler(*args):
  File "C:\Users\username\Projets\openmatb\core\dialog.py", line 91, in on_key_press
    exit(0)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0
Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x0000017B3C118940>
Traceback (most recent call last):
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 747, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 819, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\__init__.py", line 1352, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\event.py", line 408, in dispatch_event
    if handler(*args):
  File "C:\Users\username\Projets\openmatb\core\dialog.py", line 91, in on_key_press
    exit(0)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0
Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x0000017B3C118940>
Traceback (most recent call last):
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 747, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 819, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\__init__.py", line 1352, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\event.py", line 408, in dispatch_event
    if handler(*args):
  File "C:\Users\username\Projets\openmatb\core\dialog.py", line 91, in on_key_press
    exit(0)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0
Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x0000017B3C118940>
Traceback (most recent call last):
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 747, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 819, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\__init__.py", line 1352, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\event.py", line 408, in dispatch_event
    if handler(*args):
  File "C:\Users\username\Projets\openmatb\core\dialog.py", line 91, in on_key_press
    exit(0)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0
Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x0000017B3C118940>
Traceback (most recent call last):
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 747, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 819, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\__init__.py", line 1352, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\event.py", line 408, in dispatch_event
    if handler(*args):
  File "C:\Users\username\Projets\openmatb\core\dialog.py", line 91, in on_key_press
    exit(0)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0
Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x0000017B3C118940>
Traceback (most recent call last):
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 747, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 819, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\__init__.py", line 1352, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\event.py", line 408, in dispatch_event
    if handler(*args):
  File "C:\Users\username\Projets\openmatb\core\dialog.py", line 91, in on_key_press
    exit(0)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0
Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x0000017B3C118940>
Traceback (most recent call last):
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 747, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 819, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\__init__.py", line 1352, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\event.py", line 408, in dispatch_event
    if handler(*args):
  File "C:\Users\username\Projets\openmatb\core\dialog.py", line 91, in on_key_press
    exit(0)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0
Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x0000017B3C118940>
Traceback (most recent call last):
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 747, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 819, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\__init__.py", line 1352, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\event.py", line 408, in dispatch_event
    if handler(*args):
  File "C:\Users\username\Projets\openmatb\core\dialog.py", line 91, in on_key_press
    exit(0)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0
Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x0000017B3C118940>
Traceback (most recent call last):
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 747, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 819, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\__init__.py", line 1352, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\event.py", line 408, in dispatch_event
    if handler(*args):
  File "C:\Users\username\Projets\openmatb\core\dialog.py", line 91, in on_key_press
    exit(0)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0
Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x0000017B3C118940>
Traceback (most recent call last):
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 747, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 819, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\__init__.py", line 1352, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\event.py", line 408, in dispatch_event
    if handler(*args):
  File "C:\Users\username\Projets\openmatb\core\dialog.py", line 91, in on_key_press
    exit(0)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0
Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x0000017B3C118940>
Traceback (most recent call last):
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 747, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 819, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\__init__.py", line 1352, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\event.py", line 408, in dispatch_event
    if handler(*args):
  File "C:\Users\username\Projets\openmatb\core\dialog.py", line 91, in on_key_press
    exit(0)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0
Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x0000017B3C118940>
Traceback (most recent call last):
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 747, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 819, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\__init__.py", line 1352, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\event.py", line 408, in dispatch_event
    if handler(*args):
  File "C:\Users\username\Projets\openmatb\core\dialog.py", line 91, in on_key_press
    exit(0)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0
Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x0000017B3C118940>
Traceback (most recent call last):
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 747, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 819, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\__init__.py", line 1352, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\event.py", line 408, in dispatch_event
    if handler(*args):
  File "C:\Users\username\Projets\openmatb\core\dialog.py", line 91, in on_key_press
    exit(0)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0
Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x0000017B3C118940>
Traceback (most recent call last):
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 747, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 819, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\__init__.py", line 1352, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\event.py", line 408, in dispatch_event
    if handler(*args):
  File "C:\Users\username\Projets\openmatb\core\dialog.py", line 91, in on_key_press
    exit(0)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0
Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x0000017B3C118940>
Traceback (most recent call last):
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 747, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 819, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\__init__.py", line 1352, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\event.py", line 408, in dispatch_event
    if handler(*args):
  File "C:\Users\username\Projets\openmatb\core\dialog.py", line 91, in on_key_press
    exit(0)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0
Exception ignored on calling ctypes callback function: <function Win32Window._get_window_proc.<locals>.f at 0x0000017B3C118940>
Traceback (most recent call last):
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 747, in f
    result = event_handler(msg, wParam, lParam)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\win32\__init__.py", line 819, in _event_key
    self.dispatch_event(ev, symbol, modifiers)
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\window\__init__.py", line 1352, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "C:\Users\username\Projets\openmatb\venv\lib\site-packages\pyglet\event.py", line 408, in dispatch_event
    if handler(*args):
  File "C:\Users\username\Projets\openmatb\core\dialog.py", line 91, in on_key_press
    exit(0)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0

```
NB :  the fatal error was trigger because it didn't comply with the scenario I have run.

Cheers,
![2023-03-17_OpenMATB-fatal_error](https://user-images.githubusercontent.com/26115166/225946689-2e403b8a-c00f-4bed-a985-91ff54cddae2.PNG)

**Comment by benoitvalery** [comment]
Hi @thomakl, can you give some more information : platform used, scenario used, OpenMATB version used. Thanks (I think the bug has been corrected by @juliencegarra on his last commits : master branch).

**Comment by thomakl** [comment]
Hi @benoitvalery,

I am using the program : 
- platform : Windows 64,
- scenario : `default.txt` and suppress a simple parameter to make it faulty such as : `0:00:00;sysmon;`
- version : 1.2 ([last commit from 16/03](https://github.com/juliencegarra/OpenMATB/commit/a471cd008ee934ec9ddbc9ab70bd562b000ffc85))
- pyglet gui version used :` pip install git+https://github.com/jorgecarleitao/pyglet-gui.git` from [pyglet-gui](https://github.com/jorgecarleitao/pyglet-gui) (the requirements `Pyglet-gui==0.1` doesn't match).

Cheers,

**Comment by benoitvalery** [comment]
Hi @thomakl,
This issue was resolved by the last commit. Errors are now managed in a more consistent manner, which should help to prevent this Window bug. Check the master version to see if it’s OK.
