### ISSUE TITLE
running scenario_generator get error with importing plugins

### ISSUE THREAD

**Issue by thomakl** [juliencegarra/OpenMATB#24]
Hi,

I wanted to create an easy scenario with "scenario_generator.py" but I have got an error with importing the plugins : 

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\username\Projets\openmatb\scenario_generator.py", line 49, in <module>
    plugins = {'track':Track(silent=True), 
TypeError: __init__() missing 1 required positional argument: 'window'
```

Seems that the plugins miss a window parameter

Cheers

TL

**Comment by benoitvalery** [comment]
Yes, the window is now a mandatory argument of plugins. Bug fixed.
