### ISSUE TITLE
joystick_error

### ISSUE THREAD

**Issue by Rentinelau** [juliencegarra/OpenMATB#31]
Hi,
Thank you very much for your work.

When my computer was hooked up to the joystick, the code reported an error. The specific error situation is as follows:

D:\GIT\MATB\display_sysmon_and_track\OpenMATB>python main.py
Traceback (most recent call last):
  File "D:\GIT\MATB\display_sysmon_and_track\OpenMATB\main.py", line 45, in <module>
    app = OpenMATB()
  File "D:\GIT\MATB\display_sysmon_and_track\OpenMATB\main.py", line 42, in __init__
    self.scheduler.run()
  File "D:\GIT\MATB\display_sysmon_and_track\OpenMATB\core\scheduler.py", line 245, in run
    self.event_loop.run()
  File "C:\Users\CHENYUCHU\AppData\Local\Programs\Python\Python39\lib\site-packages\pyglet\app\base.py", line 169, in run
    timeout = self.idle()
  File "C:\Users\CHENYUCHU\AppData\Local\Programs\Python\Python39\lib\site-packages\pyglet\app\base.py", line 239, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "C:\Users\CHENYUCHU\AppData\Local\Programs\Python\Python39\lib\site-packages\pyglet\clock.py", line 255, in call_scheduled_functions
    item.func(dt, *item.args, **item.kwargs)
  File "D:\GIT\MATB\display_sysmon_and_track\OpenMATB\core\clock.py", line 23, in advance
    self.tick()
  File "C:\Users\CHENYUCHU\AppData\Local\Programs\Python\Python39\lib\site-packages\pyglet\clock.py", line 348, in tick
    self.call_scheduled_functions(delta_t)
  File "C:\Users\CHENYUCHU\AppData\Local\Programs\Python\Python39\lib\site-packages\pyglet\clock.py", line 255, in call_scheduled_functions
    item.func(dt, *item.args, **item.kwargs)
  File "D:\GIT\MATB\display_sysmon_and_track\OpenMATB\core\scheduler.py", line 72, in update
    self.execute_events()
  File "D:\GIT\MATB\display_sysmon_and_track\OpenMATB\core\scheduler.py", line 115, in execute_events
    self.execute_one_event(event)
  File "D:\GIT\MATB\display_sysmon_and_track\OpenMATB\core\scheduler.py", line 172, in execute_one_event
    getattr(plugin, event.command[0])()
  File "D:\GIT\MATB\display_sysmon_and_track\OpenMATB\plugins\abstract.py", line 128, in start
    self.create_widgets()
  File "D:\GIT\MATB\display_sysmon_and_track\OpenMATB\plugins\track.py", line 69, in create_widgets
    self.cursor_position = next(self.cursor_path_gen)
  File "D:\GIT\MATB\display_sysmon_and_track\OpenMATB\plugins\track.py", line 133, in compute_next_cursor_position
    self.record_input(self.alias, 'joystick_x', compx)
AttributeError: 'Track' object has no attribute 'record_input'

Could you please help me with this problem? Thank you very much

**Comment by benoitvalery** [comment]
The last commit solves this issue. See the version 1.3.0 in [releases](https://github.com/juliencegarra/OpenMATB/releases),
