### ISSUE TITLE
TypeError while generating scenario

### ISSUE THREAD

**Issue by danibene** [juliencegarra/OpenMATB#41]
Hello! I wanted to report an error that I experienced while trying to run `scenario_generator.py` with no changes:

```
Traceback (most recent call last):
  File "/mypath/OpenMATB/scenario_generator.py", line 48, in <module>
    win = Window(0, '', False, False, False, False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mypath/OpenMATB/core/window.py", line 45, in __init__
    super().__init__(fullscreen=self._fullscreen, width=self._width, height=self._height, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseWindow.__init__() got multiple values for argument 'fullscreen'
```

I am using Python 3.12.3 with the following dependencies:
```
pyglet==1.5.26
pylsl==1.16.1
pyparallel==0.2.2
rstr==3.1.0
```

I was able to get the scenario generation working here: https://github.com/juliencegarra/OpenMATB/compare/master...danibene:OpenMATB:change/scenario_generation?expand=1

By changing `win = Window(0, '', False, False, False, False)` to `win = Window()` in `scenario_generator.py`.

**Comment by juliencegarra** [comment]
Closing, this is fixed, those positional arguments were never needed.
